Repository WANNABY/WannaSDK-iOS, pull requests merged in 2022-11, with the labels that each got.

#6 5.4.1 migration
  Example/Example.xcodeproj/project.pbxproj
  Example/Example/RenderModelSelectionViewController.swift
  Example/Podfile
  Example/Podfile.lock
  README.md
Labels: documentation, enhancement

#5 Update README.md: update pods version recommendation for clients
  README.md
Labels: documentation

#7 [WK-4798] Add possibility to create session with license via deeplink (move check that license is invalid after session creation)
  Example/Example/RenderModelSelectionViewController.swift
  Example/Example/WannaSDKDefaults.swift
Labels: qa-toolkit
